### ISSUE TITLE
Improve error message for module versions that don't exist

### ISSUE THREAD

**Issue by codykonior** [VirtualEngine/Lability#375]
If you use a NonNodeData / Lability / Modules entry, with a Name and RequiredVersion, but the RequiredVersion is incorrect (e.g. that specific version doesn't exist), you get an error that is really hard to track down.

I think it hits line 56 of Expand-LabModuleCache and then fails on the call to Expand-ZipArchive because the Path property is $null and so not accepted.

If this could be improved so it tells you which module it was that caused the issue that'd be great.

**Comment by codykonior** [comment]
Here's the message that you'll get when building a lab:

```
Expand-LabModuleCache : Cannot bind argument to parameter 'Path' because it is null.
At line:31 char:23
+ ... ef] $null = Expand-LabModuleCache -Module $Module -DestinationPath $D ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Expand-LabModuleCache], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Expand-LabModuleCache

...

InnerException   : False
Exception        : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter
                   'Path' because it is null.
                      at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                   funcContext, Exception exception)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                   frame)
                      at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                      at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar,
                   Object inputToProcess)
                      at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
Message          : Cannot bind argument to parameter 'Path' because it is null.
StackTrace       :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                   funcContext, Exception exception)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                   frame)
                      at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                      at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar,
                   Object inputToProcess)
                      at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink         :
ErrorDetails     :
ErrorCategory    : InvalidData: (:) [Expand-ZipArchive], ParameterBindingValidationException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at Expand-LabModuleCache<Process>, <No file>: line 63
                   at Set-LabVMDiskModule<Process>, <No file>: line 31
                   at Set-LabVMDiskFileModule<Process>, <No file>: line 83
                   at Set-LabVMDiskFile<Process>, <No file>: line 87
                   at New-LabVirtualMachine<Process>, <No file>: line 196
                   at Start-LabConfiguration<Process>, <No file>: line 210
...
```

Here's what will break it (any version that doesn't exist):

```
    NonNodeData = @{
        Lability = @{
            Module = @(
                @{
                    RequiredVersion = '15.0.0'
                    Name = 'Pester'
                },
```

**Comment by iainbrighton** [comment]
Good catch! I'll get a more verbose/custom error message put in
